services:
  db:
    image: postgres:16
    container_name: ttt_main_db
    environment:
      POSTGRES_DB: tic_tac_toe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./backend/ttt_dump.sql:/docker-entrypoint-initdb.d/ttt_dump.sql
    ports:
      - "5432:5432"
    networks:
      - api_network

  api:
    container_name: main_api
    build:
      context: .
      dockerfile: backend/dockerfile
      target: api
    depends_on:
      - db
    networks:
      - api_network
    ports:
      - "8080:8080"

  websockets:
    container_name: websockets
    build:
      context: .
      dockerfile: backend/dockerfile
      target: websocket
    depends_on:
      - api
    networks:
      - api_network
    ports:
      - "8000:8000"

  frontend:
    container_name: main_front
    build:
      context: ./frontend
      dockerfile: dockerfile
    depends_on:
      - websockets
    networks:
      - api_network
    ports:
      - "3000:3000"

networks:
  api_network:
    driver: bridge
